/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpen_provider_wintab_WintabAccess_CursorType */

#ifndef _Included_jpen_provider_wintab_WintabAccess_CursorType
#define _Included_jpen_provider_wintab_WintabAccess_CursorType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
