/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpen_cFramework_TestType */

#ifndef _Included_jpen_cFramework_TestType
#define _Included_jpen_cFramework_TestType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpen_cFramework_TestType
 * Method:    createTestType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_createTestType
  (JNIEnv *, jobject);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getTestTypeError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpen_cFramework_TestType_getTestTypeError
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    destroyTestType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_destroyTestType
  (JNIEnv *, jobject, jint);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getUsedSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getUsedSize
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getSize
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getFirstUsedCell
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getFirstUsedCell
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getFirstFreeCell
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getFirstFreeCell
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getNextCell
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getNextCell
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getPrevCell
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getPrevCell
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
