/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpen_provider_xinput_XiBus */

#ifndef _Included_jpen_provider_xinput_XiBus
#define _Included_jpen_provider_xinput_XiBus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpen_provider_xinput_XiBus
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiBus_create
  (JNIEnv *, jclass);

/*
 * Class:     jpen_provider_xinput_XiBus
 * Method:    getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpen_provider_xinput_XiBus_getError
  (JNIEnv *, jclass);

/*
 * Class:     jpen_provider_xinput_XiBus
 * Method:    getDevicesSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiBus_getDevicesSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiBus
 * Method:    getDeviceName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpen_provider_xinput_XiBus_getDeviceName
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jpen_provider_xinput_XiBus
 * Method:    setDevice
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiBus_setDevice
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jpen_provider_xinput_XiBus
 * Method:    refreshDeviceInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiBus_refreshDeviceInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiBus
 * Method:    destroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiBus_destroy
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
