/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpen_provider_xinput_XiDevice */

#ifndef _Included_jpen_provider_xinput_XiDevice
#define _Included_jpen_provider_xinput_XiDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    getIsListening
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jpen_provider_xinput_XiDevice_getIsListening
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    setIsListening
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_jpen_provider_xinput_XiDevice_setIsListening
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    getLevelRangeMin
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiDevice_getLevelRangeMin
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    getLevelRangeMax
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiDevice_getLevelRangeMax
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    getValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiDevice_getValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    destroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiDevice_destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpen_provider_xinput_XiDevice_getError
  (JNIEnv *, jclass);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    nextEvent
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jpen_provider_xinput_XiDevice_nextEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    stopWaitingNextEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jpen_provider_xinput_XiDevice_stopWaitingNextEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    waitNextEvent
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jpen_provider_xinput_XiDevice_waitNextEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    getLastEventTime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jpen_provider_xinput_XiDevice_getLastEventTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    getLastEventType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiDevice_getLastEventType
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    getLastEventButton
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_xinput_XiDevice_getLastEventButton
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_xinput_XiDevice
 * Method:    refreshLevelRanges
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jpen_provider_xinput_XiDevice_refreshLevelRanges
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
