/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpen_provider_wintab_WintabAccess */

#ifndef _Included_jpen_provider_wintab_WintabAccess
#define _Included_jpen_provider_wintab_WintabAccess
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
#undef jpen_provider_wintab_WintabAccess_LEVEL_TYPE_X
#define jpen_provider_wintab_WintabAccess_LEVEL_TYPE_X 0L
#undef jpen_provider_wintab_WintabAccess_LEVEL_TYPE_Y
#define jpen_provider_wintab_WintabAccess_LEVEL_TYPE_Y 1L
#undef jpen_provider_wintab_WintabAccess_LEVEL_TYPE_PRESSURE
#define jpen_provider_wintab_WintabAccess_LEVEL_TYPE_PRESSURE 2L
#undef jpen_provider_wintab_WintabAccess_LEVEL_TYPE_TILT_AZIMUTH
#define jpen_provider_wintab_WintabAccess_LEVEL_TYPE_TILT_AZIMUTH 3L
#undef jpen_provider_wintab_WintabAccess_LEVEL_TYPE_TILT_ALTITUDE
#define jpen_provider_wintab_WintabAccess_LEVEL_TYPE_TILT_ALTITUDE 4L
#undef jpen_provider_wintab_WintabAccess_LEVEL_TYPE_SIDE_PRESSURE
#define jpen_provider_wintab_WintabAccess_LEVEL_TYPE_SIDE_PRESSURE 5L
#undef jpen_provider_wintab_WintabAccess_LEVEL_TYPE_ROTATION
#define jpen_provider_wintab_WintabAccess_LEVEL_TYPE_ROTATION 6L
#undef jpen_provider_wintab_WintabAccess_BUTTON1_MASK
#define jpen_provider_wintab_WintabAccess_BUTTON1_MASK 1L
#undef jpen_provider_wintab_WintabAccess_BUTTON2_MASK
#define jpen_provider_wintab_WintabAccess_BUTTON2_MASK 2L
#undef jpen_provider_wintab_WintabAccess_BUTTON3_MASK
#define jpen_provider_wintab_WintabAccess_BUTTON3_MASK 4L
#undef jpen_provider_wintab_WintabAccess_PK_CONTEXT
#define jpen_provider_wintab_WintabAccess_PK_CONTEXT 1L
#undef jpen_provider_wintab_WintabAccess_PK_STATUS
#define jpen_provider_wintab_WintabAccess_PK_STATUS 2L
#undef jpen_provider_wintab_WintabAccess_PK_TIME
#define jpen_provider_wintab_WintabAccess_PK_TIME 4L
#undef jpen_provider_wintab_WintabAccess_PK_CHANGED
#define jpen_provider_wintab_WintabAccess_PK_CHANGED 8L
#undef jpen_provider_wintab_WintabAccess_PK_SERIAL_NUMBER
#define jpen_provider_wintab_WintabAccess_PK_SERIAL_NUMBER 16L
#undef jpen_provider_wintab_WintabAccess_PK_CURSOR
#define jpen_provider_wintab_WintabAccess_PK_CURSOR 32L
#undef jpen_provider_wintab_WintabAccess_PK_BUTTONS
#define jpen_provider_wintab_WintabAccess_PK_BUTTONS 64L
#undef jpen_provider_wintab_WintabAccess_PK_X
#define jpen_provider_wintab_WintabAccess_PK_X 128L
#undef jpen_provider_wintab_WintabAccess_PK_Y
#define jpen_provider_wintab_WintabAccess_PK_Y 256L
#undef jpen_provider_wintab_WintabAccess_PK_Z
#define jpen_provider_wintab_WintabAccess_PK_Z 512L
#undef jpen_provider_wintab_WintabAccess_PK_NORMAL_PRESSURE
#define jpen_provider_wintab_WintabAccess_PK_NORMAL_PRESSURE 1024L
#undef jpen_provider_wintab_WintabAccess_PK_TANGENT_PRESSURE
#define jpen_provider_wintab_WintabAccess_PK_TANGENT_PRESSURE 2048L
#undef jpen_provider_wintab_WintabAccess_PK_ORIENTATION
#define jpen_provider_wintab_WintabAccess_PK_ORIENTATION 4096L
#undef jpen_provider_wintab_WintabAccess_PK_ROTATION
#define jpen_provider_wintab_WintabAccess_PK_ROTATION 8192L
#undef jpen_provider_wintab_WintabAccess_TU_NONE
#define jpen_provider_wintab_WintabAccess_TU_NONE 0L
#undef jpen_provider_wintab_WintabAccess_TU_INCHES
#define jpen_provider_wintab_WintabAccess_TU_INCHES 1L
#undef jpen_provider_wintab_WintabAccess_TU_CENTIMETERS
#define jpen_provider_wintab_WintabAccess_TU_CENTIMETERS 2L
#undef jpen_provider_wintab_WintabAccess_TU_CIRCLE
#define jpen_provider_wintab_WintabAccess_TU_CIRCLE 3L
#undef jpen_provider_wintab_WintabAccess_HWC_INTEGRATED
#define jpen_provider_wintab_WintabAccess_HWC_INTEGRATED 1L
#undef jpen_provider_wintab_WintabAccess_HWC_TOUCH
#define jpen_provider_wintab_WintabAccess_HWC_TOUCH 2L
#undef jpen_provider_wintab_WintabAccess_HWC_HARDPROX
#define jpen_provider_wintab_WintabAccess_HWC_HARDPROX 4L
#undef jpen_provider_wintab_WintabAccess_HWC_PHYSID_CURSORS
#define jpen_provider_wintab_WintabAccess_HWC_PHYSID_CURSORS 8L
/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_create
  (JNIEnv *, jclass);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpen_provider_wintab_WintabAccess_getError
  (JNIEnv *, jclass);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getNativeBuild
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getNativeBuild
  (JNIEnv *, jclass);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getValue
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    nextPacket
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jpen_provider_wintab_WintabAccess_nextPacket
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jpen_provider_wintab_WintabAccess_getEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    setEnabled
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_jpen_provider_wintab_WintabAccess_setEnabled
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    enable
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_jpen_provider_wintab_WintabAccess_enable
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getLevelRange
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_jpen_provider_wintab_WintabAccess_getLevelRange
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getCursor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getCursor
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getTime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jpen_provider_wintab_WintabAccess_getTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getButtons
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getButtons
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getCursorTypeOrdinal
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getCursorTypeOrdinal
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getRawCursorType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getRawCursorType
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getCursorName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpen_provider_wintab_WintabAccess_getCursorName
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getPacketRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getPacketRate
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpen_provider_wintab_WintabAccess_getDeviceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getDeviceHardwareCapabilities
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getDeviceHardwareCapabilities
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getPhysicalId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getPhysicalId
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getButtonCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getButtonCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getButtonNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jpen_provider_wintab_WintabAccess_getButtonNames
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getCapabilityMask
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_getCapabilityMask
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    destroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_provider_wintab_WintabAccess_destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    getSystemCursorEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jpen_provider_wintab_WintabAccess_getSystemCursorEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_provider_wintab_WintabAccess
 * Method:    setSystemCursorEnabled
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_jpen_provider_wintab_WintabAccess_setSystemCursorEnabled
  (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
