#!/bin/bash
# Generates the providerNativeBuild.properties file

# 1: the directory where the svn revision is taken
getRevision(){
	# warning: you should call svn update before svn info
	revision=$(svn info "$1" | grep 'Last Changed Rev' | awk -F ':' '{print($2)}')
}

# $@: all the directories to combine
getCombinedRevision(){
	combinedRevision=0
	for i in "$@"
	do
		getRevision "$i"
		echo --- $i revision: $revision
		combinedRevision=$(($combinedRevision+$revision))
	done
}

echo updating svn src/main/c...
# I use symlinks everywhere so it is safer to change to the target dir:
originalDir=$(pwd)
cd src/main/c
svn up 
cd $originalDir

propertyFile="$originalDir/nativeBuild.properties"
echo propertyFile=$propertyFile

cd svnRepository/current
echo \# DO NOT EDIT THIS FILE - it is generated by updateNativeBuildProperties.sh > $propertyFile
getCombinedRevision "trunk/src/main/c/linux" "trunk/src/main/c/utils"
echo jpen.provider.xinput.nativeBuild=$combinedRevision >> $propertyFile
getCombinedRevision "trunk/src/main/c/windows" "trunk/src/main/c/utils"
echo jpen.provider.wintab.nativeBuild=$combinedRevision >> $propertyFile
# nicarran: disable to set it manually because the osx native files are being provided by marcello:
# getCombinedRevision "src/main/c/osx"
combinedRevision=201
echo jpen.provider.osx.nativeBuild=$combinedRevision >> $propertyFile