/* % [{
% (C) Copyright 2008 JPen Developers and individual contributors.
% See the jpen-copyright.txt file in the jpen distribution for a full
% listing of individual contributors.
%
% This file is part of jpen.
%
% jpen is free software: you can redistribute it and/or modify
% it under the terms of the GNU Lesser General Public License as published by
% the Free Software Foundation, either version 3 of the License,
% or (at your option) any later version.
%
% jpen is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU Lesser General Public License for more details.
%
% You should have received a copy of the GNU Lesser General Public License
% along with jpen.  If not, see <http://www.gnu.org/licenses/>.
% }] */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jpen_cFramework_TestType */

#ifndef _Included_jpen_cFramework_TestType
#define _Included_jpen_cFramework_TestType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jpen_cFramework_TestType
 * Method:    createTestType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_createTestType
  (JNIEnv *, jobject);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getTestTypeError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jpen_cFramework_TestType_getTestTypeError
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    destroyTestType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_destroyTestType
  (JNIEnv *, jobject, jint);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getUsedSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getUsedSize
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getSize
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getFirstUsedCell
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getFirstUsedCell
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getFirstFreeCell
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getFirstFreeCell
  (JNIEnv *, jclass);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getNextCell
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getNextCell
  (JNIEnv *, jclass, jint);

/*
 * Class:     jpen_cFramework_TestType
 * Method:    getPrevCell
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jpen_cFramework_TestType_getPrevCell
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
